// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5905;

import edu.wpi.first.wpilibj.ADXRS450_Gyro;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static final double EASE_INCREMENT = 0.05;

	public static final int RIGHT_GAMEPAD_JOYSTICK = 5;

	public static final int LEFT_GAMEPAD_JOYSTICK = 1;

	public static SpeedController driveTrainSpeedController1;
    public static SpeedController driveTrainSpeedController2;
    public static SpeedController driveTrainSpeedController3;
    public static SpeedController driveTrainSpeedController4;
    public static RobotDrive driveTrainRobotDrive21;    
    public static ADXRS450_Gyro driveTrainGyro;
    

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainSpeedController1 = new Victor(0);
        LiveWindow.addActuator("DriveTrain", "FRONT_RIGHT_SIDE_SPEED_CONTROLLER", (Victor) driveTrainSpeedController1);
        
        driveTrainSpeedController2 = new Victor(1);
        LiveWindow.addActuator("DriveTrain", "FRONT_LEFT_SIDE_SPEED_CONTROLLER", (Victor) driveTrainSpeedController2);
        
        driveTrainSpeedController3 = new Victor(2);
        LiveWindow.addActuator("DriveTrain", "BACK_RIGHT_SIDE_SPEED_CONTROLLER", (Victor) driveTrainSpeedController3);
        
        driveTrainSpeedController4 = new Victor(3);
        LiveWindow.addActuator("DriveTrain", "BACK_LEFT_SIDE_SPEED_CONTROLLER", (Victor) driveTrainSpeedController4);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainSpeedController1, driveTrainSpeedController2, driveTrainSpeedController3, driveTrainSpeedController4);
        
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1);

       

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        
        driveTrainGyro = new ADXRS450_Gyro();
        
    }
}
