// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5905;

import edu.wpi.first.wpilibj.ADXL362;
import edu.wpi.first.wpilibj.ADXRS450_Gyro;
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.AnalogGyro;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Victor;
import edu.wpi.first.wpilibj.interfaces.Accelerometer;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static final double EASE_INCREMENT = 0.05;
	
	//MAX SPEED OF JUST DRIVETRAIN
	public static final double robotSpeed = 1;

	public static final int RIGHT_GAMEPAD_JOYSTICK_Y = 5;
	public static final int LEFT_GAMEPAD_JOYSTICK_Y = 1;
	public static final int LEFT_GAMEPAD_TRIGGER = 2;
	public static final int RIGHT_GAMEPAD_TRIGGER = 3;
	
	public static final double INTAKE_SPEED = 0.3;
	public static final double OUTTAKE_SPEED = 1;


	
	public static SpeedController FRONT_RIGHT_SPEED_CONTROLLER;
    public static SpeedController BACK_RIGHT_SPEED_CONTROLLER;
    public static SpeedController FRONT_LEFT_SPEED_CONTROLLER;
    public static SpeedController BACK_LEFT_SPEED_CONTROLLER;
    public static SpeedController ARM_SPEED_CONTROLLER;
    public static SpeedController ARM_RIGHT_SPEED_CONTROLLER;
    public static SpeedController ARM_LEFT_SPEED_CONTROLLER;

    
    public static RobotDrive driveTrain41;    
    public static ADXRS450_Gyro driveTrainGyro;
	public static ADXL362 driveTrainAccel;
    

    public static void init() {
    	
    	ARM_LEFT_SPEED_CONTROLLER = new Victor(5);
    	
    	ARM_RIGHT_SPEED_CONTROLLER = new Victor(6);
   
        FRONT_RIGHT_SPEED_CONTROLLER = new Victor(3);
        LiveWindow.addActuator("DriveTrain", "FRONT_RIGHT_SIDE_SPEED_CONTROLLER", (Victor) FRONT_RIGHT_SPEED_CONTROLLER);
       
        BACK_RIGHT_SPEED_CONTROLLER = new Victor(1);
        LiveWindow.addActuator("DriveTrain", "BACK_RIGHT_SIDE_SPEED_CONTROLLER", (Victor) BACK_RIGHT_SPEED_CONTROLLER);
        
        FRONT_LEFT_SPEED_CONTROLLER = new Victor(2);
        LiveWindow.addActuator("DriveTrain", "FRONT_LEFT_SIDE_SPEED_CONTROLLER", (Victor) FRONT_LEFT_SPEED_CONTROLLER);
                
        BACK_LEFT_SPEED_CONTROLLER = new Victor(0);
        LiveWindow.addActuator("DriveTrain", "BACK_LEFT_SIDE_SPEED_CONTROLLER", (Victor) BACK_LEFT_SPEED_CONTROLLER);
        
        ARM_SPEED_CONTROLLER = new Victor(4);
        LiveWindow.addActuator("Arm", "ARM_SPEED_CONTROLLER", (Victor) ARM_SPEED_CONTROLLER);
                
        driveTrain41 = new RobotDrive(FRONT_LEFT_SPEED_CONTROLLER, BACK_LEFT_SPEED_CONTROLLER, FRONT_RIGHT_SPEED_CONTROLLER,  BACK_RIGHT_SPEED_CONTROLLER);     
        
        driveTrain41.setSafetyEnabled(true);
        driveTrain41.setExpiration(0.1);
        driveTrain41.setSensitivity(0.5);
        
        //MAX OUTPUT OF ENTIRE ROBOT
        driveTrain41.setMaxOutput(0.3);
         
        driveTrainGyro = new ADXRS450_Gyro();
        driveTrainAccel = new ADXL362(Accelerometer.Range.k2G);
        
        
    }
}
