// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc.team5905.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc.team5905.subsystems.*;

/**
 *
 */
public class AutonomousCommands extends CommandGroup {


    public AutonomousCommands() {

        // Add Commands here:
        // e.g. addSequential(new Command1());
        //      addSequential(new Command2());
        // these will run in order.

        // To run multiple commands at the same time,
        // use addParallel()
        // e.g. addParallel(new Command1());
        //      addSequential(new Command2());
        // Command1 and Command2 will run in parallel.

        // A command group will require all of the subsystems that each member
        // would require.
        // e.g. if Command1 requires chassis, and Command2 requires arm,
        // a CommandGroup containing them would require both the chassis and the
        // arm.
        	
    	
    	//For Rough Terrain: 1 power @ .6 max output, 3 seconds
    	//addSequential(new GoStraightPowerTime(1, 3));
    	//For Low Bar: .75 power @ .6 max output, 2.75 seconds
    	//addSequential(new GoStraightPowerTime(.75, 2.75));
//    	addSequential(new AutoArmDown(0.5));
//    	addSequential(goUnderLowbar());
//    	addSequential(goOverRockWall());
    	addSequential(goOverRoughTerrain());
//    	addSequential(goOverRamparts());
//    	addSequential(goOverMoat());
//    	addSequential(AutoArmDown());
//    	addSequential(new AutoOuttake(.5));
//    	addSequential(new TurnAround());
    	
 
    } 
    
    private GoStraightPowerTime goOverRockWall(){
    	return (new GoStraightPowerTime(1, 2.75));
    }
    
    private GoStraightPowerTime goOverRoughTerrain() {
    	return (new GoStraightPowerTime(0.75, 2.75));
    }
    
    private GoStraightPowerTime goOverRamparts(){
    	return (new GoStraightPowerTime(1, 3.5));
    }
    
    private GoStraightPowerTime goUnderLowbar(){
    	return (new GoStraightPowerTime(-0.5, 3.5));
    }
    
    private GoStraightPowerTime goOverMoat(){
    	return (new GoStraightPowerTime(1, 3));
    }
}
